Fix docs for component with no default parameters
gdsfactory\components\containers\
add_fiber_array_optical_south_electrical_north.py
    Added default values for parameters to fix docs generation error.

    Run `make docs`, first error:
    "...gdsfactory\docs\components.rst:187: WARNING: Exception occurred
     in plotting components-12..."

    With last traceback being:
    TypeError: add_fiber_array_optical_south_electrical_north() missing
    4 required positional arguments: 'component', 'pad',
    'grating_coupler', and 'cross_section_metal'.

    Issue: 
    `docs/write_cells.py` couldn't handle functions that has
    arguments with no default value in their signature.

    Arguments:
    `component`, `pad`, `grating_coupler`, `cross_section_metal`

    Solution:
    add default values for `ComponentSpec` typed arguments as strings
    e.g. "component = 'straight_heater_metal'"

    Reasons:
    Because other functions like `add_termination`,`splitter_tree` etc.
    has default values provided as strings for `ComponentSpec` typed
    arguments.

    Default arguments values are taken from unit test file
    for this function:
    `tests\components\containers\test_add_fiber_array_optical_south_electrical_north.py`

    Error can be seen at GitHub Actions run:
    https://github.com/gdsfactory/gdsfactory/actions/runs/20535944022/job/58994155722#logs

    Test plan:
    Visually controlled that plot for
    `add_fiber_array_optical_south_electrical_north` has been generated at
    `gdsfactory/docs/_build/html/components.html#gdsfactory.components.containers.add_fiber_array_optical_south_electrical_north``

.gitignore
move entry "docs/components.rst" into docs/.gititgnore file.

docs\.gitignore
add "components.rst" from .gitignore

docs\write_cells.py
    - add description docstring in the header