Fix documentation typos and 'make docs' errors
Most errors here were encountered in error messages from `make docs` command.

docs\contribution.md - added reference for installation instruction for contributors - Code of conduct is referenced in web, instead of ``,   this generates warning "WARNING: document isn't included in any toctree"

gdsfactory/components/mzis/mzi.py
https://gdsfactory.github.io/gdsfactory/components.html#gdsfactory.components.mzis.mzi
Multiple errors for:
mzi.py:docstring of gdsfactory.components.mzis.mzi.mzi:25: ERROR: Unknown target name: "top".
mzi.py:docstring of gdsfactory.components.mzis.mzi.mzi:25: ERROR: Unknown target name: "bot".
`top_` and `bot_` in docstrings are rendered as references.
- Added escape sequence for underscore. `top_`->`top\\_`,
  same for `bot_`->`bot\\_`. Source: https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#escaping-mechanism
  Double backslash is needed because of python string escaping.

gdsfactory/components/pcms/greek_cross.py
https://gdsfactory.github.io/gdsfactory/components.html#gdsfactory.components.pcms.greek_cross
docstring of gdsfactory.components.pcms.greek_cross.greek_cross:28: ERROR: Unexpected indentation.
docstring of gdsfactory.components.pcms.greek_cross.greek_cross:30: WARNING: Block quote ends without a blank line; unexpected unindent.
docstring of gdsfactory.components.pcms.greek_cross.greek_cross:31: WARNING: Enumerated list ends without a blank line; unexpected unindent.
- fixed references rendering
- added vertical line to symbolic picture
- checked visual in locally generated docs

gdsfactory/components/quantum/coupler_capacitive.py
https://gdsfactory.github.io/gdsfactory/components.html#gdsfactory.components.quantum.coupler_capacitive
 ERROR: Error in "code" directive: maximum 1 argument(s) allowed, 41 supplied.
- add empty line after .code rst directive
- checked visual in locally generated docs, symbolic picture is
  rendered correctly

gdsfactory/components/spirals/spiral_inductor.py
https://gdsfactory.github.io/gdsfactory/components.html#gdsfactory.components.spirals.spiral_inductor
markdown python codeblocks do not render correctly in sphinx
- delete example from docstring
- checked visual in locally generated docs

gdsfactory/components/waveguides/straight_heater_doped.py
function `straight_heater_doped_strip()`
https://gdsfactory.github.io/gdsfactory/components.html#gdsfactory.components.waveguides.straight_heater_doped_strip
.straight_heater_doped_strip:19: ERROR: Error in "code" directive:
maximum 1 argument(s) allowed, 31 supplied.
straight_heater_doped_strip:36: WARNING: Explicit markup ends without a blank line; unexpected unindent.
straight_heater_doped_strip:38: ERROR: Unexpected indentation.
- add empty line after .code rst directive
- removed r at the start of docstring to avoid raw string interpretation
- checked visual in locally generated docs, both code blocks
  render correctly

notebooks/11_best_practices.ipynb
 - updated wording for clarity